// Shared console tile data — logos + ready flags for every console, including ones not yet
// built (shown as "Em breve" placeholders). Used by both the /consoles page and the Nav
// hover flyout, so this lives in one place instead of being duplicated between them.
export const CONSOLES = [
  { id: 'xbox360',    label: 'Xbox 360',    color: 'xbox',       ready: true,  logo: '/logos/xbox360.svg'    },
  { id: 'ps1',        label: 'PS1',         color: 'ps1',        ready: true,  logo: '/logos/ps1.svg'        },
  { id: 'ps2',        label: 'PS2',         color: 'ps',         ready: true,  logo: '/logos/ps2.svg'        },
  { id: 'ps3',        label: 'PS3',         color: 'ps3',        ready: true,  logo: '/logos/ps3.svg'        },
  { id: 'snes',       label: 'SNES',        color: 'snes',       ready: true,  logo: '/logos/snes.svg'       },
  { id: 'nsw',        label: 'Switch',      color: 'nsw',        ready: true,  logo: '/logos/nsw.svg'        },
  { id: 'n64',        label: 'N64',         color: 'n64',        ready: true,  logo: '/logos/n64.svg'        },
  { id: 'gamecube',   label: 'GameCube',    color: 'gcube',      ready: true,  logo: '/logos/gamecube.svg'   },
  { id: 'wii',        label: 'Wii',         color: 'wii',        ready: true,  logo: '/logos/wii.svg'        },
  { id: 'ps4',        label: 'PS4',         color: 'ps4',        ready: true,  logo: '/logos/ps4.svg'        },
  { id: 'xboxone',    label: 'Xbox One',    color: 'xboxone',    ready: false, logo: '/logos/xboxone.svg'    },
  { id: 'xboxseries', label: 'Xbox Series', color: 'xboxseries', ready: false, logo: '/logos/xboxseries.svg' },
  { id: 'pc',         label: 'PC',          color: 'pc',         ready: false, logo: '/logos/pc.svg'         },
  { id: 'gba',        label: 'GBA',         color: 'gba',        ready: true,  logo: '/logos/gba.svg'        },
  { id: 'gbc',        label: 'GBC',         color: 'gbc',        ready: false, logo: '/logos/gbc.svg'        },
  { id: '3ds',        label: '3DS',         color: 'n3ds',       ready: true,  logo: '/logos/3ds.svg'        },
  { id: 'xboxorig',   label: 'Xbox',        color: 'xboxorig',   ready: false, logo: '/logos/xboxorig.svg'   },
  { id: 'ps5',        label: 'PS5',         color: 'ps5',        ready: false, logo: '/logos/ps5.svg'        },
  { id: 'wiiu',       label: 'Wii U',       color: 'wiiu',       ready: false, logo: '/logos/wiiu.svg'       },
  { id: 'nds',        label: 'Nintendo DS', color: 'nds',        ready: false, logo: '/logos/nds.svg'        },
  { id: 'dsi',        label: 'Nintendo DSi',color: 'dsi',        ready: false, logo: '/logos/dsi.svg'        },
  { id: 'psp',        label: 'PSP',         color: 'psp',        ready: false, logo: '/logos/psp.svg'        },
  { id: 'vita',       label: 'PS Vita',     color: 'vita',       ready: false, logo: '/logos/vita.svg'       },
]

export const ACCENT_MAP = {
  xbox:       { border: 'border-xbox/40',   bg: 'hover:bg-xbox/10'   },
  ps1:        { border: 'border-slate-400/40', bg: 'hover:bg-slate-800/20' },
  ps:         { border: 'border-blue-600/40', bg: 'hover:bg-blue-900/20' },
  ps3:        { border: 'border-cyan-600/40', bg: 'hover:bg-cyan-900/20' },
  snes:       { border: 'border-red-700/40',  bg: 'hover:bg-red-900/20'  },
  n64:        { border: 'border-blue-500/40', bg: 'hover:bg-blue-900/20' },
  gcube:      { border: 'border-purple-600/40', bg: 'hover:bg-purple-900/20' },
  nsw:        { border: 'border-red-500/40', bg: 'hover:bg-white/10' },
  ps4:        { border: 'border-blue-600/40', bg: 'hover:bg-blue-900/20' },
  xboxone:    { border: 'border-xbox/40',     bg: 'hover:bg-xbox/10'      },
  xboxseries: { border: 'border-xbox/40',     bg: 'hover:bg-xbox/10'      },
  pc:         { border: 'border-sky-500/40',  bg: 'hover:bg-sky-900/20'   },
  gba:        { border: 'border-indigo-600/40', bg: 'hover:bg-indigo-900/20' },
  gbc:        { border: 'border-violet-500/40', bg: 'hover:bg-violet-900/20' },
  n3ds:       { border: 'border-red-600/40',  bg: 'hover:bg-red-900/20'   },
  wii:   { border: 'border-gray-500/40', bg: 'hover:bg-gray-800/20' },
  xboxorig:   { border: 'border-xbox/40',     bg: 'hover:bg-xbox/10'      },
  ps5:        { border: 'border-blue-700/40', bg: 'hover:bg-blue-900/20' },
  wiiu:       { border: 'border-teal-500/40', bg: 'hover:bg-teal-900/20' },
  nds:        { border: 'border-blue-400/40', bg: 'hover:bg-blue-900/20' },
  dsi:        { border: 'border-neutral-400/40', bg: 'hover:bg-neutral-800/20' },
  psp:        { border: 'border-slate-400/40', bg: 'hover:bg-slate-800/20' },
  vita:       { border: 'border-indigo-400/40', bg: 'hover:bg-indigo-900/20' },
}
